### PR TITLE
Implement goto-Sun

### LINKED ISSUE #26: Go to Sun
@pkgw You mentioned something about a "go to Sun" function that will put the view on the Sun without our having to enter an RA/Dec (which changes every day).  I haven't been able to find documentation for this. Can you advise, please?  Thanks!

### PR DESCRIPTION
**Pull request by pkgw**
We add the magic function call needed to get this working.

Closes #26.

### CODE REVIEW

**Comment by pkgw** [comment]
I fixed the indentation in the JavaScript file so the diff has a lot in it, but the key change is in the commit ed066e8348d2885bad537b18d97f14756bfc5651.

**Comment by patudom** [comment]
Thank you @pkgw!  In your version of the clickerator are the image overlays showing up? 

Go to Sun works on single-click for me, but none of the overlays are appearing now. I can look into the missing overlays, but I want to make sure this is an issue that actually needs solving and isn't something weird that's happening on my end.  (I cleared cache already).  Thanks!

Screen Shot 2020-03-26 at 11 01 51 AM

**Comment by pkgw** [comment]
Good point! I just pushed a commit that should fix this issue, I think.

**Comment by patudom** [comment]
Working here now too.  Thank you, @pkgw!

**Pull request merged**
