### PR TITLE
Troubleshoot Orion Nebula Spitzer+Hubble image overlay

### PR DESCRIPTION
**Pull request by patudom**
@pkgw - this is the WTML file I'm using where the image overlay for the Spitzer + Hubble image is not showing up. In the WTML file created by WWT, the object was generically named "Orion Nebula" and I thought maybe there was some issue of name redundancy, so I renamed it "Orion Nebula Spitzer" in my WTML.  (But all the other instances of Orion Nebula images are already uniquely named, so I'm guessing this isn't the issue).  With or without "Spitzer" in the name, the Spitzer overlay does not appear, but it shows the Hubble Probes the Great Orion Nebula overlay instead.

### CODE REVIEW

**Comment by pkgw** [comment]
Hm, I think it's working for me. Below is what I get, which looks like the right image.

Screenshot from 2020-03-23 16-28-19

If that's not what you're seeing, try clearing your browser cache?

**Comment by patudom** [comment]
Interesting.  Clearing the cache and using the version with "Spitzer" appended fixed my issue.  But when I tried deleting "Spitzer" and clearing cache again, it went back to using the wrong image overlay, so I guess the unique name is important.  Why is the client choosing the Hubble image to overlay when the WTML names "Orion Nebula" rather than "Hubble Probes the Great Orion Nebula"? (It doesn't really matter for troubleshooting this specific instance, but it's helpful for me to understand for the future why it's behaving this way.)  Thanks!

**Comment by pkgw** [comment]
@patudom When WWT looks up images by name, it just does a search through its list of all available images, and returns the first image whose name *contains* the requested name, anywhere, case-insensitively. So with the original name, your result was probably the first thing that it happened to find that contained "Orion Nebula" anywhere in its name.

It's nice to have some flexibility, but this algorithm could be improved. We should at least prefer exact matches, and possibly prefer prefix matches ("starts with" vs. "contains anywhere") tests. But, for instance, looking at the data files I see several images whose names are exactly "Orion Nebula", so an even more robust approach doesn't seem unreasonable.

**Comment by patudom** [comment]
@pkgw I see - so adding "Spitzer" required WWT to search through the WTML data for that unique name?  What's confusing is that WWT did know to use the more zoomed out field of view associated with the larger image, but maybe it's grabbing the overlay link and the BaseDegreesPerTile in different ways.  I will try not to sweat the details and will make sure all our objects are independently named going forward.  Thanks!

**Pull request merged**
